### ISSUE TITLE
Location Error

### ISSUE THREAD

**Issue by samarthesh** [abhi7585/weather_app_nodejs#1]
Unable to find required data for this location, Please try another location
Getting this message tried for various location but still got same result
What to do?
![Screenshot (1706)](https://user-images.githubusercontent.com/49289959/117873041-fc372400-b2bc-11eb-9c76-31fa8258fed8.png)

**Comment by abhi7585** [comment]
You must type the name of the city. That the query executed in the backend takes the input as a city name. That's why it says "unable to fetch for this location." Let me add something inside the placeholder to make it understandable. Thank you.

**Comment by abhi7585** [comment]
![Screenshot (108)](https://user-images.githubusercontent.com/54246710/117919284-590cfb80-b30a-11eb-98b2-5d2226ea576f.png)

It is giving this result. So it is working for the input. Have updated the placeholder for a better understanding of input.

Here:-

![Screenshot (109)](https://user-images.githubusercontent.com/54246710/117919501-b86b0b80-b30a-11eb-8990-531bc5216f92.png)

**Comment by samarthesh** [comment]
Ya now its working fine
